services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: api_gateway
    ports:
      - "8080:8080"
    env_file:
      - .env

  database:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: database
    ports:
      - "50051:50051"
    env_file:
      - .env

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: auth
    ports:
      - "50052:50052"
    env_file:
      - .env

  chat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: chat
    ports:
      - "8000:8000"
    env_file:
      - .env

  smtp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_SERVICE: smtp
    ports:
      - "50053:50053"
    env_file:
      - .env

  postgres:
    image: postgres:latest
    env_file:
      - ./postgres.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # УДАЛИТЬ


volumes:
  pgdata: